CREATE TABLE students (
  id BIGINT IDENTITY PRIMARY KEY,
  full_name NVARCHAR(255) NOT NULL,
  dob DATE NULL,
  phone VARCHAR(30) NULL,
  note NVARCHAR(1000) NULL,
  created_at DATETIME2 DEFAULT SYSDATETIME()
);
